name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: github-action
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.6
      - name : Install display library
        run: sudo apt-get install libpangoft2-1.0
      - name: Build with Maven
        run: |
          mvn -version
          mvn -B package --file pom.xml -Dtestfx.robot=glass -Dglass.platform=Monocle -Dmonocle.platform=Headless -Dprism.order=sw -Dprism.text=t2k